import type { Abi } from 'viem';

/**
 * ABI for the DiscordPortal contract.
 * Extracted from the compiled contract artifacts to avoid cross-package imports.
 */
export const discordPortalAbi: Abi = [
  {
    inputs: [
      { internalType: 'address[]', name: 'modules', type: 'address[]' },
      { internalType: 'address', name: 'router', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'InsufficientFee', type: 'error' },
  { inputs: [], name: 'InvalidSchema', type: 'error' },
  { inputs: [], name: 'InvalidShortString', type: 'error' },
  { inputs: [], name: 'InvalidSignature', type: 'error' },
  { inputs: [], name: 'InvalidSignatureLength', type: 'error' },
  { inputs: [], name: 'InvalidSubject', type: 'error' },
  { inputs: [], name: 'NotImplemented', type: 'error' },
  { inputs: [], name: 'OnlyPortalOwner', type: 'error' },
  { inputs: [], name: 'SenderIsNotSubject', type: 'error' },
  {
    inputs: [{ internalType: 'string', name: 'str', type: 'string' }],
    name: 'StringTooLong',
    type: 'error',
  },
  { inputs: [], name: 'WithdrawFail', type: 'error' },
  { anonymous: false, inputs: [], name: 'EIP712DomainChanged', type: 'event' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    inputs: [],
    name: 'SCHEMA_ID',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SIGNER_ADDRESS',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'schemaId', type: 'bytes32' },
          { internalType: 'uint64', name: 'expirationDate', type: 'uint64' },
          { internalType: 'bytes', name: 'subject', type: 'bytes' },
          { internalType: 'bytes', name: 'attestationData', type: 'bytes' },
        ],
        internalType: 'struct AttestationPayload',
        name: 'attestationPayload',
        type: 'tuple',
      },
      { internalType: 'bytes[]', name: 'validationPayloads', type: 'bytes[]' },
    ],
    name: 'attest',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'attestationRegistry',
    outputs: [{ internalType: 'contract AttestationRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'schemaId', type: 'bytes32' },
          { internalType: 'uint64', name: 'expirationDate', type: 'uint64' },
          { internalType: 'bytes', name: 'subject', type: 'bytes' },
          { internalType: 'bytes', name: 'attestationData', type: 'bytes' },
        ],
        internalType: 'struct AttestationPayload[]',
        name: 'attestationPayloads',
        type: 'tuple[]',
      },
      { internalType: 'bytes[][]', name: 'validationPayloads', type: 'bytes[][]' },
    ],
    name: 'bulkAttest',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32[]', name: 'attestationIds', type: 'bytes32[]' },
      {
        components: [
          { internalType: 'bytes32', name: 'schemaId', type: 'bytes32' },
          { internalType: 'uint64', name: 'expirationDate', type: 'uint64' },
          { internalType: 'bytes', name: 'subject', type: 'bytes' },
          { internalType: 'bytes', name: 'attestationData', type: 'bytes' },
        ],
        internalType: 'struct AttestationPayload[]',
        name: 'attestationsPayloads',
        type: 'tuple[]',
      },
      { internalType: 'bytes[][]', name: 'validationPayloads', type: 'bytes[][]' },
    ],
    name: 'bulkReplace',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32[]', name: 'attestationIds', type: 'bytes32[]' }],
    name: 'bulkRevoke',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'eip712Domain',
    outputs: [
      { internalType: 'bytes1', name: 'fields', type: 'bytes1' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'version', type: 'string' },
      { internalType: 'uint256', name: 'chainId', type: 'uint256' },
      { internalType: 'address', name: 'verifyingContract', type: 'address' },
      { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
      { internalType: 'uint256[]', name: 'extensions', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'fee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getModules',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'moduleRegistry',
    outputs: [{ internalType: 'contract ModuleRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'modules',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'portalRegistry',
    outputs: [{ internalType: 'contract PortalRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'attestationId', type: 'bytes32' },
      {
        components: [
          { internalType: 'bytes32', name: 'schemaId', type: 'bytes32' },
          { internalType: 'uint64', name: 'expirationDate', type: 'uint64' },
          { internalType: 'bytes', name: 'subject', type: 'bytes' },
          { internalType: 'bytes', name: 'attestationData', type: 'bytes' },
        ],
        internalType: 'struct AttestationPayload',
        name: 'attestationPayload',
        type: 'tuple',
      },
      { internalType: 'bytes[]', name: 'validationPayloads', type: 'bytes[]' },
    ],
    name: 'replace',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'attestationId', type: 'bytes32' }],
    name: 'revoke',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'router',
    outputs: [{ internalType: 'contract IRouter', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'attestationFee', type: 'uint256' }],
    name: 'setFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceID', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address payable', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
